<?php 
ob_start();
session_start();

$step = $_GET["step"];
$bookmark = $_GET["bookmark"]; 
?>
<HTML>
<HEAD>
<TITLE> 電腦教室使用調查填報系統 </TITLE>
<meta charset="UTF-8">
<link href="<?php echo $this->baseUrl('css/bootstrap.css') ?>" rel="stylesheet" />
<link href="<?php echo $this->baseUrl('font-awesome-4.7.0/css/font-awesome.css') ?>" rel="stylesheet" />
<script src="<?php echo $this->baseUrl('js/jquery-1.11.3.min.js') ?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap.js') ?>"></script>
</HEAD>
<style>
body{
    font-family: Microsoft JhengHei;
}
</style>

<body>
<center>
<h1>電腦教室使用調查填報系統</h1>
<br/>
</center>

<div class="container">	
	<div class="row">
		<!-- **************** menu **************** -->
		<div class="col-md-12">
			<button type="button" class="btn btn-lg <?php echo ($step=='step1')?'btn-success':'btn-default';?>" 
			onclick="location.href='<?php echo $this->baseUrl('crm/index?step=step1&school_year='.$_SESSION['school_year'].'&semester='.$_SESSION['semester']); ?>'">
			1.填寫電腦教室基本資訊
			</button> 

			&nbsp;<i class="fa fa-chevron-right fa-lg" aria-hidden="true"></i>&nbsp;
			<button type="button" class="btn btn-lg <?php echo ($step=='step2')?'btn-danger':'btn-default';?>"
			onclick="location.href='<?php echo $this->baseUrl('crm/index?step=step2&school_year='.$_SESSION['school_year'].'&semester='.$_SESSION['semester'].'&roomid=null'); ?>'">
			2.填寫電腦教室上課班級
			</button> 
			&nbsp;<i class="fa fa-chevron-right fa-lg" aria-hidden="true"></i>&nbsp;
			<button type="button" class="btn btn-lg <?php echo ($step=='step3')?'btn-info':'btn-default';?>"
			onclick="location.href='<?php echo $this->baseUrl('crm/index?step=step3&school_year='.$_SESSION['school_year'].'&semester='.$_SESSION['semester']); ?>'">
			3.查看電腦調查表
			</button> 
		</div>
		<!-- **************** step0 **************** -->
		<div class="col-md-12" id="step0" style="<?php echo ($step!='step0')?'display:none':''; ?>">
			<div class="col-md-6">
			<h3>系助理您好：麻煩填報本學期電腦教室使用狀況。</h3>
			<p>請按上方按鈕開始第一步</p>
			</div>
		</div>
		<!-- **************** step1 **************** -->
		<div class="col-md-12" id="step1" style="<?php echo ($step!='step1')?'display:none':''; ?>">
			<div class="col-md-4">		
				<form class="form-horizontal" method='post' action="<?php echo $this->baseUrl('crm/index');?>">
					<input type="hidden" name="school_year" value="105">
					<input type="hidden" name="semester" value="2">
					<h3 class="text-center text-success">電腦教室基本資料</h3>
					<div class="alert alert-success">
						<div class="form-group">
							<label class="col-sm-4 control-label">電腦教室編號</label>
							<div class="col-sm-8">
								<input class="form-control" name="room_num" type="text" placeholder="I5201">
							</div>
						</div>			
						<div class="form-group">
							<label class="col-sm-4 control-label">電腦教室名稱</label>
							<div class="col-sm-8">
								<input class="form-control" name="room_name" type="text" placeholder="多媒體電腦教室">
							</div>
						</div>			
						<div class="form-group">
							<label class="col-sm-4 control-label">個人電腦數量</label>
							<div class="col-sm-8">
								<div class="input-group">
									<input class="form-control" name="pc_num" type="text">
									<span class="input-group-addon">台</span>
								</div>
							</div>
						</div>			
						<div class="form-group">
							<label class="col-sm-4 control-label">Server數量</label>
							<div class="col-sm-8">
								<div class="input-group">
									<input class="form-control" name="sever_num" type="text" placeholder="若無Server，請寫0">
									<span class="input-group-addon">台</span>
								</div>
							</div>
						</div>			
						<div class="form-group">
							<label class="col-sm-4 control-label">作業系統名稱</label>
							<div class="col-sm-8">
								<?php 
								$oslist = $this->os ;
								if($oslist){ 
									foreach($oslist as $os){
										echo '<div class="checkbox">';
										echo '<label><input type="checkbox" name="os[]" value="'.$os['id'].'">'.$os['name'].'</label>';
										echo '</div>';
									}
								}
								?>	
							</div>
						</div>			
						<div class="form-group">
							<label class="col-sm-4 control-label">教學媒體名稱</label>
							<div class="col-sm-8">
								<?php 
								$softwarelist = $this->software ;
								if($softwarelist){ 
									foreach($softwarelist as $software){
										echo '<div class="checkbox">';
										echo '<label><input type="checkbox" name="software[]" value="'.$software['id'].'">'.$software['name'].'</label>';
										echo '</div>';
									}
								}
								?>	 
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label"></label>
							<div class="col-sm-8">
								<input class="form-control" name="school_year"	value="<?php echo $_SESSION['school_year'] ?>" type="hidden">
								<input class="form-control" name="semester"		value="<?php echo $_SESSION['semester'] ?>" type="hidden">
								
								<input name="action" type="submit" class="btn btn-success" value="新增教室" />
							</div>
						</div>

					</div>			
				</form>
			</div>
			<div class="col-md-8" >
				<h3 class="text-center text-success">電腦教室列表</h3>
				<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
					<thead>
						<tr class="success">
							<th>學年</th>
							<th>學期</th>
							<th>教室編號</th>
							<th>教室名稱</th>
							<th>個人電腦數量</th>
							<th>Server數量</th>
							<th>刪除</th>
						</tr>
					</thead>
					<tbody>
						<?php $roomlist = $this->computer_room ;
						if($roomlist){ 
						foreach($roomlist as $room){
						?>	
						<tr>
							<td><?php echo $room['school_year']?></td>	
							<td><?php echo $room['semester']?></td>
							<td><?php echo $room['room_num']?></td>
							<td><?php echo $room['room_name']?></td>
							<td><?php echo $room['pc_num']?></td>
							<td><?php echo $room['sever_num']?></td>
							<td><i class="fa fa-trash" aria-hidden="true"></i></td>
						</tr>	
						<?php 

						$year 		= $room['school_year'];
						$semester	= $room['semester'];
						$department = $room['department'];
						}
						}else{
						echo "<tr><td colspan='7'>目前尚未新增任何電腦教室</td></tr>";
						}
						?>	    
					</tbody>
				</table>		
			</div>
		</div>
		<!-- **************** step2 **************** -->
		<div class="col-md-12" id="step2" style="<?php echo($step!='step2')?'display:none':''; ?>">
			<div class="col-md-3">	
				</br>
				<div class="list-group">
				<?php
				if($roomlist){ 		
				?>	
				<a href="#" class="list-group-item"><?php echo $room['department'].'電腦教室'; ?></a>
				<?php foreach($roomlist as $room){ ?>
				<a  href="<?php echo $this->baseUrl('crm/index?step=step2&roomid='. $room['id']); ?>" 
					class="list-group-item <?php echo ($room['id'] == $_GET['roomid'])?'list-group-item-danger':''; ?>">
				<?php echo $room['room_num'].'-'.$room['room_name']; ?>
				</a>
				<?php 		}
				} 
				?>
				</div>
			</div>
			<div class="col-md-9">	

				<!-- Trigger the modal with a button -->

				<?php if($_GET['roomid'] == 'null'){ 
				echo '</br>
				<h4 class="text-danger">請先點選左側教室</h4>
				<h4 class="text-danger">
				<i class="fa fa-hand-o-left fa-2x" aria-hidden="true"></i>
				<i class="fa fa-hand-o-left fa-2x" aria-hidden="true"></i>
				<i class="fa fa-hand-o-left fa-2x" aria-hidden="true"></i>
				</h4>
				'; 
				}else{ ?>

				</br>
				<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#lecture">
					<i class="fa fa-plus" aria-hidden="true"></i> 新增上課班級
				</button></br></br>
				<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
					<thead>
						<tr class="danger">
							<th>班級</th>
							<th>人數</th>
							<th>上課時數</th>
							<th>任課老師</th>
							<th>課程名稱</th>
							<th>學制代號</th>
							<th>刪除</th>
						</tr>
					</thead>
					<tbody>
						<?php $lecturelist = $this->lecture_list ;
						if($lecturelist){ 
							foreach($lecturelist as $l){
						?>	
						<tr>
							<td><?php echo $l['lesson_name']?></td>	
							<td><?php echo $l['student_num']?></td>
							<td><?php echo $l['hour']?></td>
							<td><?php echo $l['teacher_name']?></td>
							<td><?php echo $l['lecture_name']?></td>
							<td><?php echo $l['school_code']?></td>
							<td>
							<a href='<?php echo $this->baseUrl('/crm/index?step=step2&action=delectLecture&id='. $l['id'].'&roomid='.$_GET['roomid']) ?>'>刪除</a>
							<!-- 
							 <button class="btn btn-danger" data-toggle="modal" data-target="#myModal">
							<i class="fa fa-trash-o" aria-hidden="true"></i>
							<a href=''>刪除</a>
							</button>
							-->
							</td>
						</tr>	
						<?php 
							}
						}else{
							echo "<tr><td colspan='7'>目前尚未新增任何上課班級</td></tr>";
						}
					?>	    
					</tbody>
				</table>

				<?php } ?>
				<!-- Modal -->
				<div id="lecture" class="modal fade" role="dialog">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title text-danger">新增班級資料</h4>
							</div>
								<form class="form-horizontal" method="post" action="<?php echo $this->baseUrl('crm/index');?>">
							<div class="modal-body">
								<input type="hidden" class="form-control" name="rid" value="<?php echo $_GET['roomid']; ?>">
								<div class="form-group">
									<label class="col-sm-3 control-label">班級</label>
									<div class="col-sm-9">
										<input type="text" class="form-control" name="lesson_name" placeholder="班級">
									</div>
								</div>			
								<div class="form-group">
									<label class="col-sm-3 control-label">人數</label>
									<div class="col-sm-9">
										<input type="text" class="form-control" name="student_num" placeholder="人數">
									</div>
								</div>			
								<div class="form-group">
									<label class="col-sm-3 control-label">上課時數</label>
									<div class="col-sm-9">
										<input type="text" class="form-control" name="hour" placeholder="上課時數">
									</div>
								</div>			
								<div class="form-group">
									<label class="col-sm-3 control-label">任課老師</label>
									<div class="col-sm-9">
										<div class="input-group">
											<input type="text" class="form-control" name="teacher_name" placeholder="任課老師">
											<span class="input-group-addon">老師</span>
										</div>
									</div>
								</div>			
								<div class="form-group">
									<label class="col-sm-3 control-label">課程名稱</label>
									<div class="col-sm-9">
										<input type="text" class="form-control" name="lecture_name" placeholder="課程名稱">
									</div>
								</div>			
								<div class="form-group">
									<label class="col-sm-3 control-label">學制代號</label>
									<div class="col-sm-9">
										<select class="form-control" name="school_code">
											<option>請選擇</option>
											<option value="C">C-日二技</option>
											<option value="4">4-日四技</option>
											<option value="U">U-在職班二技</option>
											<option value="A">A-在職班四技</option>
											<option value="E">E-在職專班四技</option>
											<option value="P">P-進修專校</option>
											<option value="9">9-教學學程</option>
											<option value="G">G-日間研究所</option>
											<option value="K">K-夜間研究所</option>
											<option value="1">1-學士班後第二專長</option>
										</select> 
									</div>
								</div>
							</div>
							<div class="modal-footer">
								<input name="action" type="submit" class="btn btn-danger" value="新增課程"/>
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
								</form>	
							</div>
						</div>
					</div>
				</div>

			</div>	
		</div>
		<!-- **************** step3 **************** -->
		<div class="col-md-12" id="step3" style="<?php echo($step!='step3')?'display:none':''; ?>">
			<div class="row">
				<div class="col-md-12">	
					<h3 class="text-center text-info">
					<?php 
					$row=array();
					$roomlist = $this->computer_room ;
					if($roomlist){ 
						$i=0;
						foreach($roomlist as $r){
							echo ($i==0)?$r['school_year'].'學年度　第'.$r['semester'].'學期　'.$r['department'].'　電腦教室使用調查表':'';
							$i++;
						}
					}		 
					?>	
					</h3>
					<table class="table table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr class="info">
							<th>電腦教室(名稱及編號)</th>
							<th>PC</br>數量</th>
							<th>Server</br>數量</th>
							<th>作業系統名稱</th>
							<th>教學媒體名稱</th>
							<th>班級</th>
							<th>人數</th>
							<th>每週</br>上課</br>時數</th>
							<th>任課</br>老師</th>
							<th>課程名稱</th>
							<th>學制</br>代號</th>
							</tr>
						</thead>
						<tbody>
							<?php 
							if($roomlist){ 
								foreach($roomlist as $r){
							?> 
									<tr>
										<td class="<?php echo "td".$r['id']; ?>" rowspan=""><?php echo $r['room_num'].' '.$r['room_name'];?></td>			
										<td class="<?php echo "td".$r['id']; ?>" rowspan=""><?php echo $r['pc_num'];?></td>			
										<td class="<?php echo "td".$r['id']; ?>" rowspan=""><?php echo $r['sever_num'];?></td>
										<td class="<?php echo "td".$r['id']; ?>" rowspan="">
											<?php 
											$oslist = $this->os_list ;
											if($oslist){ 
												foreach($oslist as $os){
													echo ($os['computer_room_id'] == $r['id'])? $os['os_name']."</br>": "" ;
												}
											}
											?>	 
										</td>
										<td class="<?php echo "td".$r['id']; ?>" rowspan="">
											<?php 
											$softwarelist = $this->software_list ;
											if($softwarelist){ 
												foreach($softwarelist as $sw){
													echo ($sw['computer_room_id'] == $r['id'])? $sw['software_name']."</br>": "" ;
												}
											}
											?>	 
										</td>							
										<?php 
										$count = 0; //第幾次
										$sum   = 0; //總共幾次
										$lecturelist = $this->lecture ;
										
										if($lecturelist){ 
											foreach($lecturelist as $l){
												if($l['computer_room_id'] == $r['id']){
													$sum++;
												if($count == 0){
													echo "<td>".$l['lesson_name']."</td>".
															"<td>".$l['student_num']."</td>".
															"<td>".$l['hour']."</td>".
															"<td>".$l['teacher_name']."</td>".
															"<td>".$l['lecture_name']."</td>".
															"<td>".$l['school_code']."</td>";
															$count = 1;
															$student_num+=$l['student_num'];
															$hour+=$l['hour'];

												}else if($count == 1){
													echo "<tr><td>".$l['lesson_name']."</td>".
														"<td>".$l['student_num']."</td>".
														"<td>".$l['hour']."</td>".
														"<td>".$l['teacher_name']."</td>".
														"<td>".$l['lecture_name']."</td>".
														"<td>".$l['school_code']."</td></tr>";

													$student_num+=$l['student_num'];
													$hour+=$l['hour'];
												}
												}

											}
										}
										?>	 
									</tr>
									<?php $row[$r['id']] = $sum;
											echo 
											"<tr class='danger'>
												<th colspan='6'>合計</th>
												<th><span style='color:red'>".$student_num."</span></th>
												<th><span style='color:red'>".$hour."</span></th>
												<th colspan='3'></th>
											</tr>";
									
									$student_num=0;
									$hour=0;

								}
							}
							?>	    
						</tbody>
						<tfoot>
							<tr 'info'><th colspan='11'>------------總計-------------</th></tr>
						</tfoot>
					</table>
				</div>
			</div>


		</div>



	</div>
</div>

<script>
$(document).ready(function(){
	<?php 
	if($roomlist){ 
		foreach($roomlist as $r){
	?>	
		$('.td<?php echo $r['id']; ?>').attr('rowspan','<?php echo $row[$r['id']];?>');
	<?php 
		}
	}?>
});
</script>
</body>
</HTML>