<div class="container">
	<div class="container">
		<div class="row">
			<div class="col-md-6">	
				<h3 class="text-center text-info"><i class="fa fa-desktop" aria-hidden="true"></i> 作業系統列表</h3>
				<table class="table table-striped table-bordered" cellspacing="0" width="100%">
					<thead>
						<tr class="info">
							<th><i class="fa fa-desktop" aria-hidden="true"></i> 作業系統名稱</th>
							<!-- <th>valid</th> -->
							<th><i class='fa fa-trash-o' aria-hidden='true'></i> 刪除</th>
						</tr>
					</thead>
					<tbody>
					<?php 
					$oslist = $this->os ;
					if($oslist){ 
						foreach($oslist as $os){
					?>	
						<form method='post' action="<?php echo $this->baseUrl('crm/crm/os');?>">
						<tr>
							<input name="os_id" type="hidden" value="<?php echo $os['id'];?>" />
							<td><?php echo $os['name'];?></td>
							<!-- <td><?php //echo $os['valid'];?></td> 
							<td>
								<button class="btn btn-danger" data-toggle="modal" data-target="#myModal" onClick="get_os('<?php //echo $os['name']; ?>')">
									<i class="fa fa-pencil" aria-hidden="true"></i>
								</button>
							</td>-->			
							<td>
								<input id="delect" name="action" type="submit" class="btn btn-danger" value="刪除作業系統"  onclick="return confirm('是否刪除【<?php echo $os['name'];?>】');"/>
							</td>
						</tr>
						</form>
					<?php				
						}
					}
					?>	    
					</tbody>
				</table>
				<div class="alert alert-info">			
					<form class="form-inline" method='post' action="<?php echo $this->baseUrl('/crm/crm/os');?>">
						<div class="form-group">
							<label><i class="fa fa-plus" aria-hidden="true"></i> 可在此新增所需系統：</label>
							<input class="form-control" name="os_name" type="text" placeholder="作業系統名稱">
						</div>
						<input name="action" type="submit" class="btn btn-primary" value="新增作業系統" />
					</form>
				</div>
			</div>
			<div class="col-md-6">	
				<h3 class="text-center text-warning"><i class="fa fa-desktop" aria-hidden="true"></i> 教學軟體列表</h3>
				<table class="table table-striped table-bordered" cellspacing="0" width="100%">
					<thead>
						<tr class="warning">
							<th><i class="fa fa-desktop" aria-hidden="true"></i> 教學軟體名稱</th>
							<!-- <th>valid</th> -->
							<th><i class='fa fa-trash-o' aria-hidden='true'></i> 刪除</th>
						</tr>
					</thead>
					<tbody>
					<?php 
					$softwarelist = $this->software ;
					if($softwarelist){ 
						foreach($softwarelist as $sw){
					?>	
						<form method='post' action="<?php echo $this->baseUrl('crm/crm/os');?>">
						<tr>
							<input name="software_id" type="hidden" value="<?php echo $sw['id'];?>" />
							<td><?php echo $sw['name'];?></td>
							<!-- <td><?php //echo $sw['valid'];?></td> 
							<td>
								<button class="btn btn-danger" data-toggle="modal" data-target="#myModal" onClick="get_os('<?php //echo $os['name']; ?>')">
									<i class="fa fa-pencil" aria-hidden="true"></i>
								</button>
							</td>-->			
							<td>
								<input name="action" type="submit" class="btn btn-danger" value="刪除教學軟體"  onclick="return confirm('是否刪除【<?php echo $os['name'];?>】');"/>
							</td>
						</tr>
						</form>
					<?php				
						}
					}
					?>	    
					</tbody>
				</table>
				<div class="alert alert-warning">			
					<form class="form-inline" method='post' action="<?php echo $this->baseUrl('/crm/crm/os');?>">
						<div class="form-group">
							<label><i class="fa fa-plus" aria-hidden="true"></i> 可在此新增所需軟體：</label>
							<input class="form-control" name="software_name" type="text" placeholder="軟體名稱">
						</div>
						<input name="action" type="submit" class="btn btn-warning" value="新增教學軟體" />
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">
function get_os(osname)
{
	$('#os_name').empty();
	$('#os_valid').empty();
	$('#os_name').val(osname);
	$('#os_valid').val(valid);
}	
</script>

</script>
